
[context.content-service.environment]
  SPACE_IDS = "51126 51127"
  OAUTH_TOKEN = "SXJVRJEavlvir0mtsgWN3gtt-45470-5tA_3-ajjsd4p5ni7fbt"
  ACTIVE_ENV = "content-service"

[context."production/the-final-frontier"]
  build = "yarn build"

[context."production/i-need-my-space"]
  build = "yarn build"

[context."production/the-final-frontier".environment]
  SPACE_ID = "51126"
  ACCESS_TOKEN = "HbKc4mWls4u74Rr3lrW9mgtt"
  ACTIVE_ENV = "production"

[context."production/i-need-my-space".environment]
  SPACE_ID = "51127"
  ACCESS_TOKEN = "jgBRrDrdFsjPJr2efDrhpwtt"
  ACTIVE_ENV = "production"
