
[context."production/the-final-frontier".environment]
  SPACE_ID = "51126"
  ACCESS_TOKEN = "97GrlqA78g6gEKjrE6fIcQtt"

[context."production/i-need-my-space".environment]
  SPACE_ID = "51127"
  ACCESS_TOKEN = "jgBRrDrdFsjPJr2efDrhpwtt"
  
[context.production]
  build = "echo Nothing to do here"
